# https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL: '/'
languageCode: 'en-us'
title: 'Nerves Project'

# https://gohugo.io/variables/site/#the-siteparams-variable
params:
  description: >
    Nerves is the open-source platform and infrastructure you need to build,
    deploy, and securely manage your fleet of IoT devices at speed and scale.

# https://gohugo.io/content-management/menus/
menu:
  main:
    - identifier: about
      name: About
      url: '/about/'
      weight: 3
