# https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL: '/'
languageCode: 'en-us'
title: 'Nerves Project'
Copyright: 'The Nerves Project Authors'

# https://gohugo.io/variables/site/#the-siteparams-variable
params:
  description: >
    Nerves is the open-source platform and infrastructure you need to build,
    deploy, and securely manage your fleet of IoT devices at speed and scale.

# https://gohugo.io/content-management/menus
menu:
  main:
    - name: 'Forum'
      url: 'https://elixirforum.com/c/elixir-framework-forums/nerves-forum/74'
      weight: 1
    - name: 'Docs'
      url: 'https://hexdocs.pm/nerves'
      weight: 2
    - name: 'Blog'
      url: 'https://embedded-elixir.com'
      weight: 3
    - name: 'Tips'
      url: 'https://tips.nerves-project.org'
      weight: 4
    - name: 'Newsletter'
      url: 'https://embedded-elixir.com/page/newsletter'
      weight: 5
    - name: 'Github'
      url: 'https://github.com/nerves-project'
      weight: 6
  footer1:
    - name: 'Docs'
      url: 'https://hexdocs.pm/nerves'
      weight: 1
    - name: 'Blog'
      url: 'https://embedded-elixir.com'
      weight: 2
    - name: 'Tips'
      url: 'https://tips.nerves-project.org'
      weight: 3
    - name: 'Newsletter'
      url: 'https://embedded-elixir.com/page/newsletter'
      weight: 4
  footer2:
    - name: 'Forum'
      url: 'https://elixirforum.com/c/elixir-framework-forums/nerves-forum/74'
      pre: '<img src="/img/elixir-forum.svg" width="30rem">'
      weight: 1
    - name: 'Github'
      url: 'https://github.com/nerves-project'
      pre: '<img src="/img/github.svg" width="30rem">'
      weight: 2
    - name: 'Slack'
      url: 'https://elixir-slackin.herokuapp.com'
      pre: '<img src="/img/slack.svg" width="30rem">'
      weight: 3
    - name: 'Twitter'
      url: 'https://twitter.com/NervesProject'
      pre: '<img src="/img/twitter.svg" width="30rem">'
      weight: 4
    - name: 'Meetup'
      url: 'https://www.meetup.com/nerves'
      pre: '<img src="/img/meetup.svg" width="30rem">'
      weight: 5
